### PR TITLE
Updated diagrams

### LINKED ISSUE #157: Update Documentation Diagrams
**Description**

Update the documentation diagrams to reflect the changes since Sprint 3.

### PR DESCRIPTION
**Pull request by ZackHolmberg**
closes #157 

FinalArchitecture
ClassDiagramFinal

### CODE REVIEW

**Review by madisonfines — APPROVED** [review]
Cheers

**Comment by abhisachdev17** [comment]
Awesome work, few things: 1. Arrow back from the backup to the main in blockchain might be worth adding.  2. For mining pool class the methods should be snake case

**Comment by ZackHolmberg** [comment]
> Awesome work, few things: 1. Arrow back from the backup to the main in blockchain might be worth adding. 2. For mining pool class the methods should be snake case

Does the backup communicate back to the main blockchain?  I thought the main only passed requests onto the backup

**Comment by ZackHolmberg** [comment]
Also for some reason, I can't put the files back into draw.io to edit them so to prevent having to recreate them can we just ship them as is

**Comment by abhisachdev17** [comment]
lmao lets yolo

**Review by abhisachdev17 — APPROVED** [review]

**Pull request merged**
